# Use this file to test your server-profiles that are pushed to github.
# To use different profiles in this repo, change the SERVER_PROFILE_PATH
# When using your own repo, change the SERVER_PROFILE_URL as well. 

version: "3.1"

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/jeremybcarrier/server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingfederate
      - VERBOSE=true
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz:
